### ISSUE TITLE
hmac - which pacakge should I import?

### ISSUE THREAD

**Issue by elad-bar** [formatBCE/Tuya-Get-Keys-NodeRED#1]
amazing tool, thanks for it,
currently it fails due to missing import of package for `hmac`, which one to import?

thanks

**Comment by formatBCE** [comment]
Hi! Thanks, hope it helps you.
`HMAC` node is from `node-red-contrib-crypto-js-plus` package.

**Comment by elad-bar** [comment]
thanks, missed your message, sorry
